['diamond_ring_silver'] = { label = 'Silver Diamond Engagement Ring', weight = 100, stack = false, close = true, description = 'A silver engagement ring with a flawless diamond.' },
['diamond_ring_gold'] = { label = 'Gold Diamond Engagement Ring', weight = 100, stack = false, close = true, description = 'A luxury gold engagement ring with a bright diamond.' },
['diamond_ring_rose'] = { label = 'Rose Gold Diamond Engagement Ring', weight = 100, stack = false, close = true, description = 'A rose gold engagement ring made for a luxury proposal.' },
['wedding_band_diamond'] = { label = 'Diamond Wedding Band', weight = 100, stack = false, close = true, description = 'A diamond wedding band used during a marriage ceremony.' },
['marriage_license'] = { label = 'Marriage License', weight = 100, stack = false, close = true, description = 'Official proof of a marriage license.' },
['wedding_invitation'] = { label = 'Wedding Invitation', weight = 25, stack = false, close = true, description = 'A formal wedding invitation.' },
