CREATE TABLE IF NOT EXISTS marriages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    citizenid1 VARCHAR(50) NOT NULL,
    citizenid2 VARCHAR(50) NOT NULL,
    status VARCHAR(50) DEFAULT 'engaged',
    shared_lastname VARCHAR(50) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    married_at TIMESTAMP NULL
);

ALTER TABLE marriages
ADD COLUMN IF NOT EXISTS shared_lastname VARCHAR(50) NULL;

ALTER TABLE marriages
ADD COLUMN IF NOT EXISTS married_at TIMESTAMP NULL;
